// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || 'https://atuxocibsmflgwlwuvmv.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF0dXhvY2lic21mbGd3bHd1dm12Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODI3MzEzOTUsImV4cCI6MjA5ODMwNzM5NX0.-z83TYdQ34a1-59Ij07ZuqFV-5XFUjyFT-9P5FUtlBY';

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error('🔴 CRITICAL: Supabase env vars missing! App will not work properly.');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  }
});